### ISSUE TITLE
US7: HOME

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#1]
## Value Proposition:

**As a** user
**I want to** see a phone navigation in my contact list
**so that**  i can access to the Home page

## Description

![Bildschirmfoto 2023-06-16 um 11 38 45](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/73f8a494-387d-46a9-b142-a53109037e24)

## Acceptance Criteria

- [ ] The navigation bar should be displayed at the bottom of the screen.
- [ ] The navigation bar should consist of icons for the Home, Phone, Messages, and Settings apps.
- [ ] The icons should be displayed without any text, only the app icons should be visible.
- [ ] Clicking on the Home icon should navigate to the HOME page.
- [ ] Clicking on the Phone, Messages, or Settings icons brings user to the HOME page.
- [ ] The Navigation component should be created.
- [ ] The Navigation component should be nested within the `Home` component to display it below the main content.
- [ ] The Navigation component should be nested  in the `Contacts` component
- [ ] A Contact APP icon is displayed
- [ ] the Contact APP icon brings user back to Contacts List

## Tasks

- [ ] create branch `home`
- [ ] create `Home` component to render the main page.
- [ ] create a `Navigation` component.
- [ ] import Link to Navigation from "Next"
- [ ] Create a Navigation component that includes icons for Phone, Messages, Settings, and Home.
- [ ] Ensure that each icon has a Link and functionality that takes the user to the Home page.
- [ ] Nest the Navigation component within the Home component to display it below the main content.
- [ ] Nest the Navigation component within the Contact component to display it below.
- [ ] Create a Contact Icon with Name at the Home Page.
- [ ] Link this Icon to the Contacts page

**Comment by actyvystom** [comment]
Hey Maria, please consider the following comments:

Your **value proposition** is not following a short, clear and precise format. Please stick to the 3 sentence pattern and try to step back and imagine what a user with no knowledge about your app could do with the goal of this user story (maybe it's just a copy & paste issue :wink:).

Regarding your acceptance criteria, the scope of your user story seems too big to me.
Maybe it would be an easier approach if you start your first feature with the navigation bar and create the corresponding navbar icons, all working showing the same page (or just a simple headline). Then you could continue writing user stories for every section of your app.

**Comment by MichanNan** [comment]
LGTM 🚀
