### ISSUE TITLE
US8: Edit Contact

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#14]
## Value Proposition

**As a** user
**I want to**  be able to see details of a contact and have an option to change them
**so that**  I can update contact details anytime I see them 
​

## Description

When the user clicks on Contact information button there are 2 new things, the text/edit button ("bearbeiten") and the save "speichern" button. By clicking edit the user can change the name, number or notes (at lest the name) and by clicking the save button, the updated data is saved. These changes can be viewed in the contact list.
​
![Bildschirmfoto 2023-06-21 um 14 38 00](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/490c3317-14d5-4c4a-9f06-3bc5df14b766)

## Acceptance Criteria

- [ ] The Contact Detail Page display a new `edit` "bearbeiten" option.
- [ ] The Contact Detail Page display a new `save` "speichern" option.
- [ ] Like before only Name are required, show warning if empty.
- [ ] User can change: name, phone and note.
- [ ] The submit button (save) that triggers the contact change process.
- [ ] A success message should be displayed upon successful contact change.
- [ ] The changed contact can be seen in the contact list
      
## Tasks

- [ ] create branch `update-contact`.
- [ ] create a `edit` button/link.
- [ ] create a `save` button.
- [ ] handle the contact update process.
- [ ] Implement the logic to save the changed contact details in the database.
- [ ] Display a success message after a contact is successfully changed.
- [ ] Display a warning if the minimum name is not saved
- [ ] Test the entire flow of changing a contact.

**Comment by actyvystom** [comment]
Hi Maria, a nice one! I like the way you are defining your acceptance criteria and your task list 🚀 !
However some comments on your **value proposition**: 
- the way you describe it, I would assume that the user wants to edit all contacts at once. I suggest something like the following:

> As a user 
> I want to be able to see details of a contact and have an option to change them 
> so that I can update contact details anytime I see them

Cheers, Thomas

**Comment by MariaRiosNavarro** [comment]
done
