### ISSUE TITLE
US9: Favorite Button

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#16]
## Value Proposition

**As a** user 
**I want to** select and remove my favorites contacts
**so that**  I see them all together in another list.
​

## Description

In our contact list there are 2 new tabs that lead to the contact list itself and to a new list of favorites. In the contact list we have a new button that changes its status when clicked. This button when changing the status makes the contact to be marked as a favorite and appear in our new favorites list. In the same way you can touch this button again to remove the contact from the favorites list. 
​
![Bildschirmfoto 2023-06-22 um 10 16 50](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/fd2e3dd4-f68b-437d-abda-8b625da90e7a)

## Acceptance Criteria

- [ ] Two **tabs** are displayed at the Contacts List Page.
- [ ] The **contacts**("Kontakten") tab redirects to the existing  **Contacts List Page**.
- [ ] The **favorites** ("Favoriten")  tab takes you to the **new Favorites list**.
- [ ] In the **new Favorites list**  you will also see the same tabs that you see in **Contacts List Page**.
- [ ] In each contact there is a new button that will activate it as a favorite, or remove as favorite.
- [ ] Clicking this button on a contact will enable it to appear or be removed from the favorites list, depending on its initial status.  
- [ ] When you click this button there will be a visual change of this "button". 

## Tasks

- [ ] create branch `favoritelist`.
- [ ] create `Tab` component.
- [ ] create `TabBadget` component.
- [ ] create `FavoritesList` component.
- [ ] Add the new Favorites SVG .
- [ ] Implement the logic for the visual change of the favorites SVG.
- [ ] Implement the logic for the toggle on the new favorites SVG, so that the contact appears in the favorites list or is removed from the favorites list.

**Comment by TmWgnr** [comment]
LGTM :)
