### ISSUE TITLE
US10: Delete Contact

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#18]
## Value Proposition

**As a** user
**I want to** be able to delete contacts
**so that**  to have my contacts list organized

## Description

The user can click on the information button of each contact. And after that when the user click the edit button, the delete button will appear. Pressing this button will not delete the contact yet, but a window will appear confirming the deletion with 2 buttons: `delete the contact` and `cancel`. Only after click the `delete the contact` the contact will be deleted of the database.

![Bildschirmfoto 2023-06-23 um 09 05 02](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/d5c7900d-d6ab-4965-9a4e-8557dbb8fa5b)

## Acceptance Criteria

- [ ] Only after click the edit button, a delete button appears on the information button of each contact,
- [ ] a small window "toaster" appears below the window
- [ ] In this "toaster" display two buttons, `delete the Contact` and `cancel`.
- [ ] Just by pressing this button the contact will be deleted and will disappear from the contact list. 
      

## Tasks

- [ ] Create a new branch `delete`
- [ ] Create new button `delete`
- [ ] Implement the new button only to the aktiv `edit` page.
- [ ] Create a second "toaster" window with 2 new buttons.
- [ ] Create a second delete button in the "toaster" window.
- [ ] create a cancel button in the "toaster" window.
- [ ] handle the delete process.
- [ ] Implement the logic to delete the contact  in the database.

**Comment by ChristophLeuker** [comment]
Great work! Very detailed.
Maybe u can ask a "Are you serious to delete this contact". But thats just what i thought.

**Comment by MariaRiosNavarro** [comment]
Thanks for your proposal, but I do a phone simulation, when you delete a contact in IOS does not ask you anything, you only get that window that confirms the deletion, thus avoiding the erroneous deletion, without having to ask and "bother" the user (UX). If it was a simulation of a Desktop I would do as you say, as it is usual to get those messages on Desktop, but not on IOS or Android.
