### ISSUE TITLE
US**: contactsComponent

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#2]
##  Value proposition

As a user, I want to be able to click on the "Contacts" icon on the home screen,  that closely resembles a real mobile phone interface
​
## Description

![Bildschirmfoto 2023-06-15 um 16 18 28](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/22952706-6443-4cee-91d7-f1e0950b4e58)

## Acceptance Criteria

- [ ] the `Contacts` Icon is displayed at the screen 
- [ ] the `Contacts` Name is displayed at the screen 
- [ ] clicking on the ICON `Contacts` takes you to the `Contacts` Page/Component.
- [ ] In the `Contacts` Component we see one Heading

## Tasks

- [ ] create branch `contactsComponent`
- [ ] create `Contacts` component with only one Heading
- [ ] create `Contacts` ICON with its heading in HOME 
- [ ] add to this icon and heading a link to the `Contacts` component
