### ISSUE TITLE
US11: Settings Menu

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#20]
## Value Proposition

**As a** user 
**I want to**  to choose a profile from the saved profiles in Settings of my simulation
**so that** change the look of my application as I wish
​

## Description

There is a new page in Settings where there are 2 profiles that can be chosen alternatively. If one is active, the other is inactive and vice versa. One is always active

![Bildschirmfoto 2023-06-23 um 15 04 20](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/4c02ffdb-6441-4627-80a6-2ca637d7ed86)

## Acceptance Criteria

- [ ] You see a new page in Settings.
- [ ] On the new page you see 2 profiles headings, one for the light and one for dark.
- [ ] Each profile has a button.
- [ ] The button changes its name and appearance if it is activated or not.
- [ ] The appearance changes according to the selected profile.   ​

## Tasks

- [ ] create "settings" branch
- [ ] create `settings` page
- [ ] create a button that can change its appearance, when activated
- [ ] Implement the logic to change the buttons names and appearance
- [ ] Implement the logic to change the appearance

**Comment by sebastianwel** [comment]
Hi Maria, nice feature. For me the US is clear and understandable. 
LGTM :-)
