### ISSUE TITLE
US12: NewProfile

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#21]
## Value Proposition

**As a** user 
**I want to**  have the possibility to choose another color to the already predetermined
**so that**  I can choose the color that I want 
​
## Description

In the list of profiles in settings a new profile that can be customize.  When you click on the button as this profile, a window appears with a color input where the user can choose a color. There will be a change of appearance according to the chosen color.

![Bildschirmfoto 2023-06-25 um 14 46 46](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/7b3134ed-00b0-4a92-b86b-30aec4436c0e)

## Acceptance Criteria

- [ ] a new Profil is displayed.
- [ ] It has too a activate Buton like the others.
- [ ] If you click the activate Buton a window appears to choose a color.
- [ ] when we choose the color, the appearance is changed according to the chosen color.
      ​
## Tasks

- [ ] create branch "costumize-profile"
- [ ] create a new profile with his button.
- [ ] Implement the logic to change the appearance with the right color, when the "costumize-profile" is activated.

**Comment by ryliecc** [comment]
Very easy to understand, not too many requirements. Good user story, I like it! :)

**Comment by dimitriosxmi** [comment]
## LGTM
very straight forward and clear objective! ❤️
