### ISSUE TITLE
US13: MessageButton

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#22]
## Value Proposition

**As a** user
**I want to** display a message page
**so that**  I can imitate to send a message to one of my contacts
​

## Description
![Bildschirmfoto 2023-06-23 um 16 36 38](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/67c967c3-eea9-49d0-b4ff-0136b867a5c0)

## Acceptance Criteria

- [ ] An phone button should be displayed next to each contact on the Contacts page for the message option
- [ ] Clicking on the button redirects the user Message Page.
- [ ] On Message Page the name of the contact should be visible.
- [ ] Cancel Heading is displayed (go back to contacts)
- [ ] Heading with "New Message" is displayed
    
## Tasks
- [ ]  create a new branch MessageButton
- [ ]  create the Message component.
 - [ ] create the Message Button component.
- [ ]  Set the href attribute of the Link component to /contacts-message/${contact.id} to create the link to the Message component.
 - [ ]  Implement a route for the Message page.
- [ ]  Message component only need  the contact's name. 
 - [ ] Test the functionality to ensure the button correctly navigates to the Message Page of each Contact and displays the correct name

**Comment by CarstenJahnke** [comment]
Thats awesome 🤩📲

**Comment by nastiche** [comment]
Acceptance criteria, first line: `a MESSAGE button...`

and maybe write in the AC also: `Cancel Heading is displayed (clicking on it redirects to contacts page)`

Goody good!
