### ISSUE TITLE
US14: Phone App

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#23]
## Value Proposition

**As a** user
**I want to** click to the Phone Icon app
**so that**  i can see all my contacts 
​

## Description.

The phone icon takes us to the contact list but with the heading Phone.
![Bildschirmfoto 2023-06-23 um 16 55 34](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/9ed8554c-bcf8-4f35-9949-89f4a716a377)

## Acceptance Criteria

- [ ] The phone icon at Home and everywhere in our Simulation takes us to the contact list but with the heading Phone. (Phone Application)
- [ ] The Phone Heading is displayed at the new Page.
- [ ] All the Contacts actions button work here to. (info and call)

      
## Tasks

- [ ] create "phoneapp" branch
- [ ] create phone Page 
- [ ] import the ContactsList to the phone Page and check all routes
- [ ] Test the working flow, that all the buttons works

**Comment by CarstenJahnke** [comment]
LGTM 📲
