### ISSUE TITLE
US15: Photo Upload

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#28]
## Value Proposition

**As a** user
**I want to** be able to upload image in my simulation
**so that** i can simulate a gallery 
​

## Description

The photo gallery is active and click on it go to the new Gallery page with a Photo Gallery with a plus icon to open the input file form
​

![Bildschirmfoto 2023-06-29 um 09 54 43](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/d81542ab-69c5-48b3-b0fc-653acae27ce9)

## Acceptance Criteria

- [ ] The Photo Gallery Icon at Home is visually marked as activ (no lightgray)
- [ ] The new Page of Gallery display a Photo Gallery
- [ ] The new Page display a plus icon to open the Upload Photo Page
- [ ] the Upload Page display a input file and a save button.
​

## Tasks

- [ ] create branch `gallery`
- [ ] Use Cloudinary 
- [ ] create the api for cloudinary (get and put/patch)
- [ ] create the page Gallery
- [ ] create the upload Form

**Comment by Danielschuetzle** [comment]
great user story, LGTM 👍🏻
