### ISSUE TITLE
US16: Favorite save permanently

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#29]
## Value Proposition

**As a**  user
**I want to** save permanently my favorite Contacts
**so that** they do not disappear every time I close and reopen the application.
​

## Description

Until now only favorites could be applied but once the application was closed or reloaded, these favorites disappeared, with this US the definitive change of favorites will be made, so that when you reopen the application they will be in the state that we left when we closed the application.
​
![Bildschirmfoto 2023-06-29 um 10 02 50](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/bf7d5c85-5ca0-4bdc-8827-dad8c8a878f6)

## Acceptance Criteria

- [ ] when we do a reload the chosen favorites remain

## Tasks

- [ ]  create branch `save-favorite-permanently`
- [ ]  change the Schema to accept "favorite"
- [ ]  create the Apis to able save the favorite .
- [ ]  change the handle to save the favorite.

**Comment by Danielschuetzle** [comment]
there is an empty codeblock in the acceptance criteria and seems like some are missing. please check

**Comment by MariaRiosNavarro** [comment]
thank you, changed

**Comment by Danielschuetzle** [comment]
LGTM 💯
