### ISSUE TITLE
US***: ContactsNavigation

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#3]
## Value proposition

As a user, I want to  use the same Navigation of the HOME,  at the `Contacts` Page,  that closely resembles a real mobile phone interface

## Description

![Bildschirmfoto 2023-06-15 um 17 01 07](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/693e511c-c164-457c-98da-931c18931376)

​

## Acceptance Criteria

- [ ] view at the `Contacts` Page the Same `Navigation` of the `HOME` screen
- [ ] Links of the `Navigation` component works like at `HOME`, all redirect you to Home  ​

## Tasks

- [ ] create branch `ContactNavigation`
- [ ] Nest `Navigation` component at the `Contacts` Component
- [ ] check that all links in the `Navigation` in `Contacts` Component take me to HOME page
