### ISSUE TITLE
US17: Message Page

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#33]
## Value Proposition

**As a** user  
**I want to** click to the Message Icon app 
**so that**  i can see all my contacts

## Description

![Bildschirmfoto 2023-06-30 um 11 33 01](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/c0d27d4d-a215-4b9a-8073-5a691eb42056)

​

## Acceptance Criteria

- [ ] The message icon at Home and everywhere in our Simulation takes us to the contact list but with the heading Message (Message Application)
- [ ] The Message Heading is displayed at the new Page.
- [ ] All the Contacts actions button work here to
      ​
## Tasks

- [ ] create "messageapp" branch
- [ ] create message Page
- [ ] import the ContactsList to the message Page and check all routes
- [ ] Test the working flow, that all the buttons works

**Comment by actyvystom** [comment]
A nice one!
Somehow confusing (I guess it's just a typo or copying issue): in your **acceptance criteria** you mention that the Phone Heading is displayed, I guess you mean the messages heading? 🤔 
Cheers, Thomas

**Comment by MariaRiosNavarro** [comment]
updated 😅

**Comment by matschi3** [comment]
nothing to assume here :)
nice little US 🚀
