### ISSUE TITLE
US19 Code Refactoring

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#35]
## Value Proposition

**As a** user 
**I want to** be able to improve the code of my app
**so that** to make my application better

## Description

Code Refactoring and remove repetitive code
​

## Acceptance Criteria

- [ ] Not visually acceptance Criteria, only code

## Tasks

- [ ] create branch `refactoring`
- [ ] remove repetitive code

**Comment by Danielschuetzle** [comment]
LGTM I believe we dont need any wireframe for refactoring as far as i know 👍🏻
