### ISSUE TITLE
US20: send Message

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#36]
## Value Proposition

**As a** user
**I want to** to imitate to send a message
**so that** so that it resembles an original chat.
​
## Description
![Bildschirmfoto 2023-06-30 um 16 36 55](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/692a235d-c68f-4163-a4d8-9f3da0dcef85)

## Acceptance Criteria

- [ ] the message that has been written appears on the message screen after click enter

 ​
## Tasks

- [ ] create branch `messageactions`
- [ ] consider exchanging the input for a p
- [ ] create some useState and useEffect to handle the pseudoinput field(p) appears on another paragraph after click the enter of the Keyboard

**Comment by ghost** [comment]
Great User Story! I can understand both your vision of the outcome and your path towards it well.
