### ISSUE TITLE
US21: Contacts Photos

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#37]
## Value Proposition

**As a** user
**I want to**  be able to add photos to my contacts
**so that** recognize them quickly.
​
## Description

![Bildschirmfoto 2023-06-30 um 17 06 01](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/93e56dfc-87b3-4b73-a70a-1ecd8bd331d1)

​
## Acceptance Criteria

- [ ] The app should provide an option to upload or add photos to contacts.
- [ ] When adding a photo, the user should be able to choose from the photos already stored (or update the picture directly)
- [ ] the photo is associated with the contact and is visible in the contact list

## Tasks

- [ ] create branch "contactphoto"
- [ ] Implement the UI elements for uploading or adding photos to contacts.
- [ ] Integrate Cloudinary SDK/API into the app for photo storage and retrieval.
- [ ] Develop a mechanism to associate uploaded photos with the respective contacts.
- [ ] Modify the contact list UI to display the photos next to each contact's name.
- [ ] Test the entire flow, ensuring that photos are uploaded, associated with contacts, and displayed correctly in the contact list.

**Comment by ghost** [comment]
Quite a big story. A lot of Tasks to be considered, but it makes sense to me to see this as one process. Once again clearly written so I was able to follow your thoughts. Nice one.
