### ISSUE TITLE
US21 Message Back

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#38]
## Value Proposition

**As a** user
**I want to** to imitate to receive a message
**so that** it resembles an original chat. 
​

## Description

Shortly after the sent message appears, another message appears that simulates a chat reply.

![Bildschirmfoto 2023-07-02 um 16 06 20](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/47284e03-3621-4143-b7bd-24972f27aa1f)

​

## Acceptance Criteria

- [ ] after  the message that has been written appears, apears another message back
      ​

## Tasks

- [ ] create branch `messageback`
- [ ] use setTimeout to handle the message back.
- [ ] Testing the working flow.

**Comment by sebastianwel** [comment]
lgtm, I assume that the same massage that you have sent will then be shown again as "received" message?

**Comment by MariaRiosNavarro** [comment]
> lgtm, I assume that the same massage that you have sent will then be shown again as "received" message? 

no, the back Message will be hardcoded first, in the future, the idea is to save the answer in a form, the user himself. but not for now. Also the gray Message will be one random String
