### ISSUE TITLE
US22-Fake Login and Registration

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#39]
## Value Proposition

**As a** user
**I want to** have a login and registration page
**so that**  I can simulate a login and a registration in my Aplication
​
## Description

![Bildschirmfoto 2023-07-03 um 09 46 40](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/7319480c-574f-47bf-b9cc-6d17bdabdd4f)

## Acceptance Criteria

- [ ] A new page is display at the Beginning of my Aplication
- [ ] The Page has a form with 2 sections: login and Registration
- [ ] The Login Section has 2 inputs : email and password.
- [ ] The Login Section has a Log In button
- [ ] The​ Registration Section has 3 Inputs: password and 2 emails.
- [ ] the Registration Section has a save button
- [ ] For now the form takes you to the Home page, no matter what you fill in the forms.

## Tasks

- [ ] create branch `loginpage` 
- [ ] refactor `HOME` to one new page, HOME.
- [ ] create in  `index.js` of the Project a Login and Registration Form. (For now the form takes you to the Home page, no matter what you fill in the forms.)

**Comment by MichanNan** [comment]
LGTM 🚀
