### ISSUE TITLE
US1: ContactList

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#4]
## Value proposition

**As a** user
**I want to** see a list of my contacts
**so that** I have an overview about all contacts

## Description
![Bildschirmfoto 2023-06-16 um 14 38 48](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/5cb92cf8-1412-446f-bc93-7a0e87d97f14)

## Acceptance Criteria
- [ ] Contacts Heading is displayed 
- [ ] Contacts Names are displayed at the Contacts Page
- [ ] Contacts Pictures are displayed at the Contacts Page
- [ ] You can see a separate line below  of each Contact 
      ​

## Tasks

- [ ] create "contactList" branch
- [ ] create Contacts component.
- [ ] the Contacts Component has a  unordered list inside.
- [ ] Generate mock data for the Contacts page in a db folder.
- [ ] Create a `ContactItem` component 
- [ ] Import Image from Next in the new `ContactItem` component
- [ ] `ContactItem`  display only the name (heading) and the Image of the mock data.
- [ ]  Map the data from the mock contacts in db folder to create a list item for each contacts on the`Contacts` list Component

**Comment by mbosselmann** [comment]
Hi Maria,
great job! :octocat: I really like your user story. I have two remarks:

1. It would be great if your wireframe has a border that represents the screen size for better understanding
2. On the right side of your wireframe is a scroll bar or? I think that it is cool to show that the user can scroll vertically to see all contacts. This is something you could also add as acceptance criterion (but is not a must ;))

I hope this does help! :) Not much is missing!

**Comment by MariaRiosNavarro** [comment]
The scrolling bar is not my primary focus in this user story. My main priority is ensuring that the data is displayed correctly and effectively. 😉 As long as I can't add many contacts to my application there is no point in me bothering to build a scrolling bar without data. Mock data are very few and far between.

**Comment by MariaRiosNavarro** [comment]
wireframe is updated

**Comment by mbosselmann** [comment]
Hi Maria,
this looks good! I recommend to have a white background for your wireframe as this blends in better with your design, but this is nothing that hinders me in approving your first user story. 🥳 

In case you do not know where to change from dark mode to light mode in excalidraw, I will leave a screenshot for you:

![Screenshot 2023-06-16 at 14 48 27](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/77329824/e9559ef2-819c-422c-8fa7-b751fbbfeba3)
