### ISSUE TITLE
US2: Contact Detail Component

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#5]
## Value proposition

**As a** user
**I want to** click to the info button
**so that**   displays detailed information for each contact

## Description
![Bildschirmfoto 2023-06-16 um 11 05 55](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/00af6512-e08c-4877-83a9-3093cdae3c9c)

## Acceptance Criteria

- [ ] An information button should be displayed next to each contact on the Contacts page.
- [ ] Clicking on the button redirects the user to the detail page of the contact.
- [ ] On the contact details page, the name of the contact should be visible.
- [ ] The detail page displays the detailed information of the selected contact.
- [ ] The detail page display at least the Name of the Contact.

## Tasks

- [ ]  create branch `contactDetailComponent`
- [ ]  create the `ContactDetail` component.
- [ ]  Import Image from Next in the new  `ContactDetail`
- [ ]  The  `ContactDetail` component should include a heading for the contact's name, an Image for the Photo, a paragraph for the phone number and  a paragraph for the Note (They  can be a empty paragraphs except for the name). 
- [ ]  Create an `InfoButton` component.
- [ ]  Import the Link component from Next.js to enable navigation. Wrap in the `InfoButton` with the Link component.
- [ ]  Set the href attribute of the Link component to /contacts/${contact.id} to create the link to the detail page.
- [ ]  Implement a route for the contact detail page.
- [ ]  Add the contact ID as a parameter in the route path 
- [ ]  Import the `InfoButton` component to the `ContactItem` component 
- [ ]  Test the functionality to ensure the button correctly navigates to the detail page and displays the correct information

**Comment by TmWgnr** [comment]
looks good to me. i like the very detailed tasks. 

for me one thing is missing, but maybe its on later task: how can i go back to all contacts? 

otherwise i think you can run this US ;)

**Comment by MariaRiosNavarro** [comment]
IN subsequent steps a navigation like in a Mobile Phone will be added below. For now it is only to see the details of each contact.
