### ISSUE TITLE
US 24: Keyboard Style Issue

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#50]
## Value Proposition

**As a** user
**I want to** that the keyboard of my simulation does not change color
**so that**  it always looks good whatever the chosen theme
​

## Description
Fix the Issue with the Dark and Custom color Issue with the Keyboard. Fix the problem by creating a general keyboard for all themes, which cannot be changed, but can always be read.
<img width="391" alt="Bildschirmfoto 2023-07-10 um 07 37 59" src="https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/931b8e47-b51b-4c06-be7d-93127f9fd8a5">

​

## Acceptance Criteria

- [ ] The keyboard can be read without problems in any of the themes chosen in settings.
- [ ] Use the same Keyboard for the 3 themes (light, dark and custom)

      ​

## Tasks

- [ ] create branch "keyboardstyle"
- [ ] add class to keyboard
- [ ] use !important in the class styles for Background and Color

**Comment by LukasWeckner** [comment]
Go get that keyboard! :-)
