### ISSUE TITLE
US3: Call Component

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#6]
## Value proposition

**As a** user
**I want to**   display a call page
**so that**    I can imitate a call to one of my contacts
​
## Description

![Bildschirmfoto 2023-06-16 um 15 31 14](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/ff1ac15a-8808-473a-b54c-1eae924a6208)

## Acceptance Criteria

- [ ] An phone button should be displayed next to each contact on the Contacts page.
- [ ] Clicking on the button redirects the user Call Page.
- [ ] On Call Page the name of the contact should be visible.
- [ ] On The Call Page a hang up button red should be visible.

## Tasks

- [ ]  create a new branch `callPage`
- [ ]  create the `Call` component.
- [ ]  create the  `CallButton` component.
- [ ]  Import the Link component from Next.js to enable navigation. Wrap in the `CallButton` with the Link 
component.
- [ ]  Set the href attribute of the Link component to /contacts/${contact.id} to create the link to the `Call` component
- [ ]  Import Image from Next in the new `Call` Component.
- [ ] `Call` component should include a heading for the contact's name, a Image and the hang up red button (now non-functional).
- [ ]  Implement a route for the `Call` page.
- [ ]  Add the contact ID as a parameter in the route path
- [ ] Import the Call Button component to the ContactItem component
- [ ] Test the functionality to ensure the button correctly navigates to the Call Page and displays the correct information

**Comment by MariaRiosNavarro** [comment]
IN subsequent steps a navigation like in a Mobile Phone will be added below. For now it is only to see the details of each contact.

**Comment by nastiche** [comment]
Hi Maria,

I suggest making following changes to make this user story easier to understand:

- Value proposition:
     As a user
     I want to be able to display a call page
     so that I can imitate a call to one of my contacts

- in the Acceptance Criteria you write `On Call Page, at least the name of the contact should be visible.`, I would add the hang up button to this sentence, because a hang up button is also a must:
  - `On Call Page the name of the contact and a red hang up button should be visible.`

Maybe you should also mention in the Acceptance Criteria the optional image element on your Call Page

Nasti

**Comment by MariaRiosNavarro** [comment]
done

**Comment by nastiche** [comment]
Hmmm I am not sure that your value proposition describes exactly what the user wants to be able to do. You dont want to call your contacts, right? You just want to display a page which would look like a call to one of your contacts.

**Comment by nastiche** [comment]
I would really suggest changing the `I want to call my contacts`part of your vlaue proposition to smth like `I want to be able to display a fake call page`, otherwise I would think that you really want to implement a real call function in your app 😀 Your user is a worker of a filming team right? So he knows that he only wants to see a fake call page and to not actually call a contact.

**Comment by MariaRiosNavarro** [comment]
done
