### ISSUE TITLE
US6: Hang up Call

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#7]
## Value Proposition

**As a** user
**I want to**  be able to touch the red button 
**so that**  i can  view the list of my contacts

​
## Description

![Bildschirmfoto 2023-06-16 um 11 23 37](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/96a2e1d2-e09a-45bb-bf5c-8278021168cc)

​

## Acceptance Criteria

- [ ] when I touch/click the red button it takes me to the contact page.
      ​
## Tasks

- [ ] create a new branch `hangup`
- [ ] import Link from Next to the `Call` Component
- [ ] wrap the red button in the `Call` Component with the Link
- [ ] define the `Contacts` page as the path to that link
- [ ] Test that the Button works and takes you to the corresponding page

**Comment by rueveydaakuel** [comment]
LGTM 👍
