### ISSUE TITLE
US4:SaveData

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#8]
## Value Proposition

**As a** user
**I want to**  save all my new contacts
**so that**  are save
​
## Description

![Bildschirmfoto 2023-06-16 um 15 36 28](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/999554b5-9c7a-4b99-84cf-2f98bc42b271)

## Acceptance Criteria

 - [x]  The Contact List has a new plus icon
 - [x]  The Plus Icon brings user to the Contact Form
 - [x] The Contact Form should display the input of name without label Name but with the focus in the input
 - [x]  A warning should be displayed if the Name field is left empty, the Name input is required
 - [x]  Above the Name is a Empty Circle as a Input to upload the Foto
 - [x] The Contact Form should display the input of phone Number
 - [x] The Contact Form should display a label for the Phone Number
 - [x] The Contact Form should display the textarea of notes
 - [x]  The Contact Form should display a label for the textarea
 - [x]  The Contact Form should display submit button
 - [x]  The form should have a submit button (save) that triggers the contact addition process.
 - [x]  After submitting the form, the contact details should be saved in our database.
 - [x]  A success message should be displayed upon successful contact addition.
      ​
## Tasks

 - [x] Create a branch „saveData“.
 - [x] Create a Plus Icon at the Contacts List.
 - [x] Wrap the new Icon with a Link.
 - [x] The Link brings the User to the Contact Form Component.
 - [x] Create a `Contact Form` component.
 - [x] Set up an API endpoint or service to handle the contact addition process.
 - [x] Create a Model and Schema for the data of the Form
 - [x] Implement the logic to save the contact details in the database.
 - [x] Display a success message after a contact is successfully added.
 - [x] Display a warning if the minimum name is not saved
 - [x] Test the entire flow of adding a contact, including form validation and database integration.

**Comment by TmWgnr** [comment]
I would prefer smaller steps but i think u can do this in one UserStory :)
looks clear and good to me. 
go for it!
