### ISSUE TITLE
US5: Read Data

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#9]
## Value Proposition

**As a** user
**I want to**  display my new saved contacts
**so that** they are in my Contact list

## Description

![Bildschirmfoto 2023-06-16 um 16 09 05](https://github.com/MariaRiosNavarro/mobileSimulation-propOS/assets/118831479/17b79b4b-9ade-4cd4-92de-384508b4bed3)

​

## Acceptance Criteria

- [ ] the new contact appears on a new line in the contacts list.
- [ ] the new contact has at least one name.
- [ ] the call and info buttons should be visible next to the contact.

## Tasks

- [ ]  Create a branch `readData`.
- [ ]  Set up an API endpoint or service to handle the read addition process.
- [ ]  Implement the logic to read the contact details in the database.
- [ ]  Check that the new Data are displayed
- [ ]  Refactor in `ContactItem` component to display the name and the photo of the contact (if the photo is availeble).
- [ ]  Check that info button and call button works with the new data

**Comment by sebastianwel** [comment]
Hey Maria, looks good so far! Only one thing is the formatting of your Acceptance Criteria. I would delete the white spaces and the grey box there :-) 
Besides that, your value proposition has a missing word I guess:

> As a user
> I want to display my new saved contacts
> so that **they** are in my Contact list

Since you already set up the general logic for the database in the previous US, the rest looks fine to me 🚀

**Comment by MariaRiosNavarro** [comment]
thank you, changes done
